// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAppBlocklist(arg1:Array<string>):Promise<void>;

export function AddWebBlocklist(arg1:string):Promise<void>;

export function ClearAppBlocklist():Promise<void>;

export function ClearWebBlocklist():Promise<void>;

export function DisableAutostart():Promise<void>;

export function EnableAutostart():Promise<void>;

export function GetAppBlocklist():Promise<Array<string>>;

export function GetAutostartStatus():Promise<boolean>;

export function GetWebBlocklist():Promise<Array<string>>;

export function GetWebLogs(arg1:string,arg2:string):Promise<Array<any>>;

export function HasPassword():Promise<boolean>;

export function Login(arg1:string):Promise<boolean>;

export function RemoveAppBlocklist(arg1:Array<string>):Promise<void>;

export function RemoveWebBlocklist(arg1:string):Promise<void>;

export function Search(arg1:string,arg2:string,arg3:string):Promise<Array<any>>;

export function SetPassword(arg1:string):Promise<void>;
