// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAppBlocklist(arg1) {
  return window['go']['main']['App']['AddAppBlocklist'](arg1);
}

export function AddWebBlocklist(arg1) {
  return window['go']['main']['App']['AddWebBlocklist'](arg1);
}

export function ClearAppBlocklist() {
  return window['go']['main']['App']['ClearAppBlocklist']();
}

export function ClearWebBlocklist() {
  return window['go']['main']['App']['ClearWebBlocklist']();
}

export function DisableAutostart() {
  return window['go']['main']['App']['DisableAutostart']();
}

export function EnableAutostart() {
  return window['go']['main']['App']['EnableAutostart']();
}

export function GetAppBlocklist() {
  return window['go']['main']['App']['GetAppBlocklist']();
}

export function GetAutostartStatus() {
  return window['go']['main']['App']['GetAutostartStatus']();
}

export function GetWebBlocklist() {
  return window['go']['main']['App']['GetWebBlocklist']();
}

export function GetWebLogs(arg1, arg2) {
  return window['go']['main']['App']['GetWebLogs'](arg1, arg2);
}

export function HasPassword() {
  return window['go']['main']['App']['HasPassword']();
}

export function Login(arg1) {
  return window['go']['main']['App']['Login'](arg1);
}

export function RemoveAppBlocklist(arg1) {
  return window['go']['main']['App']['RemoveAppBlocklist'](arg1);
}

export function RemoveWebBlocklist(arg1) {
  return window['go']['main']['App']['RemoveWebBlocklist'](arg1);
}

export function Search(arg1, arg2, arg3) {
  return window['go']['main']['App']['Search'](arg1, arg2, arg3);
}

export function SetPassword(arg1) {
  return window['go']['main']['App']['SetPassword'](arg1);
}
