name: Go CI
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.1'
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install frontend dependencies
        run: cd gui && npm install
      - name: Run frontend linter
        run: cd gui && npm run lint
      - name: Run frontend formatter check
        run: cd gui && npm run format-check
      - name: Build frontend
        run: make build-frontend
      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.5.0
      - name: Run golangci-lint
        env:
          GOOS: windows
        run: |
          echo "Running golangci-lint..."
          golangci-lint run ./...
      - name: Build
        run: make build
